Added
VKhmil/Book-shop pull request #1
Opened 2024-02-21 20:32 UTC by VKhmil

Book entity representing a book with attributes such as title, author, ISBN, price, description, and cover image URL. Book service handling business logic related to managing books. Book repository providing CRUD operations for the Book entity.

2024-02-22 10:04 UTC, MentorMA requested changes

2024-02-22 10:04 UTC, MentorMA commented on src/main/java/mate/repository/impl/BookRepositoryImpl.java
> +    }
You have lombok library, lets use @requireadargsconstructor annotation instead of @Autowire

2024-02-22 10:04 UTC, MentorMA commented on src/main/java/mate/service/impl/BookServiceImpl.java
> +    }
Same situation

2024-02-22 18:06 UTC, okuzan approved these changes

2024-02-22 18:06 UTC, okuzan commented on src/main/java/mate/model/Book.java
> +
```suggestion
```

2024-02-28 09:54 UTC, Rommelua commented on src/main/java/mate/dto/CreateBookRequestDto.java
> +    private Long id;
```suggestion
```

2024-02-28 09:54 UTC, Rommelua commented on src/main/java/mate/model/Book.java
> +public class Book {
class Book should already be in the project

2024-03-01 16:51 UTC, VKhmil commented on src/main/java/mate/model/Book.java
> +public class Book {
Don't get it. What do you mean?

2024-03-01 18:05 UTC, MentorMA requested changes

2024-03-01 18:05 UTC, MentorMA commented on src/main/java/mate/DemoApplication.java
> +    private BookService bookService;
For what do you write this?

2024-03-01 18:07 UTC, VKhmil commented on src/main/java/mate/DemoApplication.java
> +    private BookService bookService;
Forget to remove

2024-03-01 18:08 UTC, MentorMA requested changes
![image](https://github.com/VKhmil/Book-shop/assets/156338484/8ab6b204-b279-4541-b14d-f3ca90b08be8)

2024-03-01 18:37 UTC, VKhmil commented on src/main/java/mate/dto/CreateBookRequestDto.java
> +    private Long id;
![image](https://github.com/VKhmil/Book-shop/assets/68187475/16909bac-26ac-4eee-b92d-8274421b249d)

2024-03-01 18:37 UTC, VKhmil commented on src/main/java/mate/dto/CreateBookRequestDto.java
> +    private Long id;
that's why it pushed again

2024-03-01 18:41 UTC, VKhmil commented on src/main/java/mate/model/Book.java
> +public class Book {
![image](https://github.com/VKhmil/Book-shop/assets/68187475/aebd6adc-166b-48ac-b5ce-41ac4b1ae4b6)
thats why it pushed again)

2024-03-03 10:40 UTC, MentorMA requested changes
![image](https://github.com/VKhmil/Book-shop/assets/156338484/803777a6-3f32-4b37-a775-cade71019b1a)
I want to see only these changes in this PR, but I find changes from the previous task

2024-03-06 18:46 UTC, Vasul-Pankiv approved these changes
approved, but remove empty lines

2024-03-06 18:46 UTC, Vasul-Pankiv commented on src/main/java/mate/dto/CreateBookRequestDto.java
> +
empty line

2024-03-06 18:46 UTC, Vasul-Pankiv commented on src/main/java/mate/dto/BookDto.java
> +
same

2024-03-10 12:14 UTC, MentorMA approved these changes

2024-03-12 16:38 UTC, merged