Tests added for BooService, and BookRepository
VKhmil/Book-shop pull request #16
Opened 2024-09-16 14:10 UTC by VKhmil

2024-09-22 17:13 UTC, VKhmil commented
![image](https://github.com/user-attachments/assets/ee01a329-b512-4bd0-b96a-188037bb44b4)

2024-09-23 06:42 UTC, liliia-ponomarenko requested changes
Great 🔥 Let's improve your solution ;)

2024-09-23 06:42 UTC, liliia-ponomarenko commented on src/test/java/com/bookappstore/controller/BookControllerTest.java
> +        }
You can use annotation SQL below the class

2024-09-23 06:42 UTC, liliia-ponomarenko commented on src/test/java/com/bookappstore/controller/BookControllerTest.java
> +    private static void teardown(DataSource dataSource) {
the same

2024-09-23 06:42 UTC, liliia-ponomarenko commented on src/test/java/com/bookappstore/controller/BookControllerTest.java
> +    void updateByValidId_ShouldReturnUpdateBook() throws Exception {
```suggestion
    void updateByValidId_ShouldReturnUpdateBook_Ok() throws Exception {
```

2024-09-23 06:42 UTC, liliia-ponomarenko commented on src/test/java/com/bookappstore/controller/CategoryControllerTest.java
> +
```suggestion
```

2024-09-23 06:42 UTC, liliia-ponomarenko commented on src/test/java/com/bookappstore/repository/BookRepositoryTest.java
> +        Category category = categoryRepository.findById(12L).get();
Don't call any other repository methods in test case

2024-09-23 06:42 UTC, liliia-ponomarenko commented on src/test/java/com/bookappstore/service/impl/BookServiceImpTest.java
> +    private Category createCategory(Long id, String name) {
I really like that in this class you put the creation of test objects into private methods, you can apply this to other test classes.

2024-09-23 06:42 UTC, liliia-ponomarenko commented on src/test/java/com/bookappstore/service/impl/BookServiceImpTest.java
> +    }
Do you need this method that just calls another method?

2024-09-23 06:42 UTC, liliia-ponomarenko commented on src/test/java/com/bookappstore/service/impl/BookServiceImpTest.java
> +    void getById_NonExistingId_ShouldReturnException() {
```suggestion
    void getById_NonExistingId_ShouldThrowsException() {
```

2024-09-23 06:42 UTC, liliia-ponomarenko commented on src/test/java/com/bookappstore/service/impl/BookServiceImpTest.java
> +    void save_NormalBook_ShouldReturnBook() {
```suggestion
    void save_ValidlBook_ShouldReturnBook() {
```

2024-09-23 06:42 UTC, liliia-ponomarenko commented on src/test/java/com/bookappstore/service/impl/BookServiceImpTest.java
> +    public void testFindAllBooksWithCategories() {
use the similar naming style for test cases ;)

2024-09-23 06:42 UTC, liliia-ponomarenko commented on src/test/java/com/bookappstore/service/impl/BookServiceImpTest.java
> +                .thenReturn(categories);
Keep all mocks in one group, good practice to follow GWT grouping as well
// Given
... 
// When
...
// Than
...

2024-09-23 06:42 UTC, liliia-ponomarenko commented on src/test/java/com/bookappstore/service/impl/CategoryServiceImplTest.java
> +class CategoryServiceImplTest {
```suggestion
@ExtendWith(MockitoExtension.class)
class CategoryServiceImplTest {
```
missed

2024-09-23 06:42 UTC, liliia-ponomarenko commented on src/test/java/com/bookappstore/service/impl/CategoryServiceImplTest.java
> +        // Ініціалізація тестових даних
```suggestion
```

2024-09-23 06:42 UTC, liliia-ponomarenko commented on src/test/java/com/bookappstore/service/impl/CategoryServiceImplTest.java
> +    void testSave() {
let's fix test names in this class ;)

2024-09-23 06:42 UTC, liliia-ponomarenko commented on src/test/resources/database/test/books/add-books-and-categories-into-table.sql
> +VALUES (12, 12), (12, 13);
Add one empty line at the end of the file (check other files)

2024-09-25 08:47 UTC, okuzan approved these changes
Good job!

2024-10-04 13:57 UTC, merged