Bookservice1
VKhmil/Book-shop pull request #8
Opened 2024-03-16 13:53 UTC by VKhmil

2024-03-16 16:18 UTC, kerrrusha requested changes
cant see pagination

2024-03-26 17:34 UTC, MAMentorFX requested changes

2024-03-26 17:34 UTC, MAMentorFX commented on src/main/java/com/bookappstore/service/impl/BookServiceImpl.java
> +        return bookRepository.findAll().stream()
Why you removed pagination?

2024-03-29 08:55 UTC, Vasul-Pankiv approved these changes

2024-04-02 13:06 UTC, merged